<a href="https://colab.research.google.com/github/ajaykumar080286/feature_engineering/blob/main/28_iterative_imputer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression

In [23]:
df=pd.read_csv("https://raw.githubusercontent.com/ajaykumar080286/feature_engineering/main/50_Startups.csv")[['R&D Spend','Administration','Marketing Spend','Profit']]/10000

In [24]:
df.head(3)

,R&D Spend,Administration,Marketing Spend,Profit
0,16.534920,13.689780,47.178410,19.226183
1,16.259770,15.137759,44.389853,19.179206
2,15.344151,10.114555,40.793454,19.105039


In [29]:
np.random.seed(9)
df = df.sample(5).copy()
df

,R&D Spend,Administration,Marketing Spend
14,11.994324,NaN,25.651292
21,7.838947,15.377343,29.973729
37,NaN,5.128314,19.702942
2,15.344151,10.114555,40.793454
44,2.217774,15.480614,NaN


In [26]:
df = df.iloc[:,0:-1]

In [30]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan

In [31]:
# Step 1 - Impute all missing values with mean of respective col

df0 = pd.DataFrame()

df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

In [32]:
# 0th Iteration
df0

,R&D Spend,Administration,Marketing Spend
14,11.994324,11.995424,25.651292
21,9.852083,15.377343,29.973729
37,9.852083,5.128314,19.702942
2,15.344151,11.995424,40.793454
44,2.217774,15.480614,29.030354


In [34]:
# Remove the col1 imputed value
df1 = df0.copy()

df1.iloc[1,0] = np.nan

df1

,R&D Spend,Administration,Marketing Spend
14,11.994324,11.995424,25.651292
21,NaN,15.377343,29.973729
37,9.852083,5.128314,19.702942
2,15.344151,11.995424,40.793454
44,2.217774,15.480614,29.030354


In [35]:
# Use first 3 rows to build a model and use the last for prediction

X = df1.iloc[[0,2,3,4],1:3]
X

,Administration,Marketing Spend
14,11.995424,25.651292
37,5.128314,19.702942
2,11.995424,40.793454
44,15.480614,29.030354


In [36]:
y = df1.iloc[[0,2,3,4],0]
y

,R&D Spend
14,11.994324
37,9.852083
2,15.344151
44,2.217774


In [37]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([5.98697235])

In [38]:
df1.iloc[1,0] = 23.14

In [39]:
df1

,R&D Spend,Administration,Marketing Spend
14,11.994324,11.995424,25.651292
21,23.140000,15.377343,29.973729
37,9.852083,5.128314,19.702942
2,15.344151,11.995424,40.793454
44,2.217774,15.480614,29.030354


In [41]:
# Remove the col2 imputed value

df1.iloc[3,1] = np.nan

df1

,R&D Spend,Administration,Marketing Spend
14,11.994324,11.995424,25.651292
21,23.140000,15.377343,29.973729
37,9.852083,5.128314,19.702942
2,15.344151,NaN,40.793454
44,2.217774,15.480614,29.030354


In [42]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[[0,1,2,4],[0,2]]
X

,R&D Spend,Marketing Spend
14,11.994324,25.651292
21,23.140000,29.973729
37,9.852083,19.702942
44,2.217774,29.030354


In [43]:
y = df1.iloc[[0,1,2,4],1]
y

,Administration
14,11.995424
21,15.377343
37,5.128314
44,15.480614


In [44]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([27.42221767])

In [45]:
df1.iloc[3,1] = 11.06

In [47]:
# Remove the col3 imputed value
df1.iloc[4,-1] = np.nan

df1

,R&D Spend,Administration,Marketing Spend
14,11.994324,11.995424,25.651292
21,23.140000,15.377343,29.973729
37,9.852083,5.128314,19.702942
2,15.344151,11.060000,40.793454
44,2.217774,15.480614,NaN


In [48]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[0:4,0:2]
X

,R&D Spend,Administration
14,11.994324,11.995424
21,23.140000,15.377343
37,9.852083,5.128314
2,15.344151,11.060000


In [49]:
y = df1.iloc[0:4,-1]
y

,Marketing Spend
14,25.651292
21,29.973729
37,19.702942
2,40.793454


In [50]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([30.62404258])

In [51]:
df1.iloc[4,-1] = 31.56
# After 1st Iteration
df1

,R&D Spend,Administration,Marketing Spend
14,11.994324,11.995424,25.651292
21,23.140000,15.377343,29.973729
37,9.852083,5.128314,19.702942
2,15.344151,11.060000,40.793454
44,2.217774,15.480614,31.560000


In [52]:
# Subtract 0th iteration from 1st iteration

df1 - df0

,R&D Spend,Administration,Marketing Spend
14,0.000000,0.000000,0.000000
21,13.287917,0.000000,0.000000
37,0.000000,0.000000,0.000000
2,0.000000,-0.935424,0.000000
44,0.000000,0.000000,2.529646


In [54]:
df2 = df1.copy()

df2.iloc[1,0] = np.nan

df2

,R&D Spend,Administration,Marketing Spend
14,11.994324,11.995424,25.651292
21,NaN,15.377343,29.973729
37,9.852083,5.128314,19.702942
2,15.344151,11.060000,40.793454
44,2.217774,15.480614,31.560000


In [55]:
X = df2.iloc[[0,2,3,4],1:3]
y = df2.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([5.30167393])

In [57]:
df2.iloc[1,0] = 23.78
df2.iloc[3,1] = np.nan
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([24.82668328])

In [59]:
df2.iloc[3,1] = 11.22
df2.iloc[4,-1] = np.nan

X = df2.iloc[0:4,0:2]
y = df2.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([33.57861535])

In [60]:
df2.iloc[4,-1] = 31.56
df2


,R&D Spend,Administration,Marketing Spend
14,11.994324,11.995424,25.651292
21,23.780000,15.377343,29.973729
37,9.852083,5.128314,19.702942
2,15.344151,11.220000,40.793454
44,2.217774,15.480614,31.560000


In [61]:
df2 - df1

,R&D Spend,Administration,Marketing Spend
14,0.00,0.00,0.0
21,0.64,0.00,0.0
37,0.00,0.00,0.0
2,0.00,0.16,0.0
44,0.00,0.00,0.0


In [62]:
df3 = df2.copy()

df3.iloc[1,0] = np.nan

df3

,R&D Spend,Administration,Marketing Spend
14,11.994324,11.995424,25.651292
21,NaN,15.377343,29.973729
37,9.852083,5.128314,19.702942
2,15.344151,11.220000,40.793454
44,2.217774,15.480614,31.560000


In [63]:
X = df3.iloc[[0,2,3,4],1:3]
y = df3.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([5.30681833])

In [65]:
df3.iloc[1,0] = 24.57
df3.iloc[3,1] = np.nan
X = df3.iloc[[0,1,2,4],[0,2]]
y = df3.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([24.78168392])

In [67]:
df3.iloc[3,1] = 11.37
df3.iloc[4,-1] = np.nan

X = df3.iloc[0:4,0:2]
y = df3.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([36.18771802])

In [68]:
df3.iloc[4,-1] = 45.53
df2.iloc[3,1] = 11.22
df3

,R&D Spend,Administration,Marketing Spend
14,11.994324,11.995424,25.651292
21,24.570000,15.377343,29.973729
37,9.852083,5.128314,19.702942
2,15.344151,11.370000,40.793454
44,2.217774,15.480614,45.530000


In [69]:
df3 - df2

,R&D Spend,Administration,Marketing Spend
14,0.00,0.00,0.00
21,0.79,0.00,0.00
37,0.00,0.00,0.00
2,0.00,0.15,0.00
44,0.00,0.00,13.97
